/**
 * Created by zahmed on 15-Oct-15.
 */

class FeatureVerification {
    static cleanPermissions(permissions) {
        if (!permissions) {
            return [];
        }
        if (!(permissions instanceof Array)) {
            return [];
        }
        return permissions;
    }

    static isPermitted(featureName: string, permissions: any = []) {
        var isAllowed = false;

        permissions = FeatureVerification.cleanPermissions(permissions);

        if (!!featureName) {
            if (permissions.indexOf(featureName) > -1) {
                isAllowed = true;
            }
        }

        return isAllowed;
    }
}

class Features {
    public static SEND_ERROR_NOFTIFICATION = "SEND_ERROR_NOFTIFICATION";
    public static EXPORT_FULFILLMENT_DELAYED = "EXPORT_FULFILLMENT_DELAYED";
    public static ITEM_STATUS_MANAGER = "ITEM_STATUS_MANAGER";
    public static EXPORT_DELISTED_ITEMS_TO_WALMART = "EXPORT_DELISTED_ITEMS_TO_WALMART";
    public static IMPORT_SO_FROM_EXTERNAL_SYSTEM: string = "IMPORT_SO_FROM_EXTERNAL_SYSTEM";
    public static IMPORT_OPPORTUNITY_FROM_EXTERNAL_SYSTEM = "IMPORT_OPPORTUNITY_FROM_EXTERNAL_SYSTEM";
    public static SALES_ORDER_IMPORT_AS_CASH_SALE = "SALES_ORDER_IMPORT_AS_CASH_SALE";
    public static UPDATE_SO_FROM_EXTERNAL_SYSTEM: string = "UPDATE_SO_FROM_EXTERNAL_SYSTEM";
    public static IMPORT_SO_GUEST_CUSTOMER: string = "IMPORT_SO_GUEST_CUSTOMER";
    public static IMPORT_SO_DUMMMY_ITEM: string = "IMPORT_SO_DUMMMY_ITEM";
    public static EXPORT_SO_TO_EXTERNAL_SYSTEM: string = "EXPORT_SO_TO_EXTERNAL_SYSTEM";
    public static EXPORT_SO_GUEST_CUSTOMER: string = "EXPORT_SO_GUEST_CUSTOMER";
    public static EXPORT_SO_DUMMMY_ITEM: string = "EXPORT_SO_DUMMMY_ITEM";
    public static EXPORT_SO_SYSTEM_NOTES: string = "EXPORT_SO_SYSTEM_NOTES";
    public static CANCEL_SO_FROM_EXTERNAL_SYSTEM: string = "CANCEL_SO_FROM_EXTERNAL_SYSTEM";
    public static CANCEL_SO_TO_EXTERNAL_SYSTEM: string = "CANCEL_SO_TO_EXTERNAL_SYSTEM";
    public static EXPORT_CUSTOMER_TO_EXTERNAL_SYSTEM: string = "EXPORT_CUSTOMER_TO_EXTERNAL_SYSTEM";
    public static IMPORT_CUSTOMER_FROM_EXTERNAL_SYSTEM: string = "IMPORT_CUSTOMER_FROM_EXTERNAL_SYSTEM";
    public static UPDATE_CUSTOMER_IF_EXISTS: string = "UPDATE_CUSTOMER_IF_EXISTS";
    public static EXPORT_ITEM_TO_EXTERNAL_SYSTEM: string = "EXPORT_ITEM_TO_EXTERNAL_SYSTEM";
    public static EXPORT_TAXCODE_SHIPPINGITEM_TO_EXTERNAL_SYSTEM: string = "EXPORT_TAXCODE_SHIPPINGITEM_TO_EXTERNAL_SYSTEM"; // *** added EXPORT_TAXCODE_SHIPPINGITEM_TO_EXTERNAL_SYSTEM in external system config
    public static EXPORT_CATEGORY_TO_EXTERNAL_SYSTEM: string = "EXPORT_CATEGORY_TO_EXTERNAL_SYSTEM";
    public static IMPORT_ITEM_FROM_EXTERNAL_SYSTEM: string = "IMPORT_ITEM_FROM_EXTERNAL_SYSTEM";
    public static EXPORT_ITEM_TIERED_PRICING: string = "EXPORT_ITEM_TIERED_PRICING";
    public static UPDATE_ITEM_TO_EXTERNAL_SYSTEM: string = "UPDATE_ITEM_TO_EXTERNAL_SYSTEM";
    public static EXPORT_INVOICE_TO_EXTERNAL_SYSTEM: string = "EXPORT_INVOICE_TO_EXTERNAL_SYSTEM";
    public static EXPORT_CASH_REFUND_TO_EXTERNAL_SYSTEM: string = "EXPORT_CASH_REFUND_TO_EXTERNAL_SYSTEM";
    public static EXPORT_ITEM_FULFILLMENT_TO_EXTERNAL_SYSTEM: string = "EXPORT_ITEM_FULFILLMENT_TO_EXTERNAL_SYSTEM";
    public static EXPORT_ITEM_FULFILLMENT_TRACKING_INFO: string = "EXPORT_ITEM_FULFILLMENT_TRACKING_INFO";
    public static EXPORT_PROMOTION_TO_EXTERNAL_SYSTEM: string = "EXPORT_PROMOTION_TO_EXTERNAL_SYSTEM";
    public static EXPORT_PRICE_LEVEL_TO_EXTERNAL_SYSTEM: string = "EXPORT_PRICE_LEVEL_TO_EXTERNAL_SYSTEM";
    public static EXPORT_PAYMENT_TERMS_TO_EXTERNAL_SYSTEM: string = "EXPORT_PAYMENT_TERMS_TO_EXTERNAL_SYSTEM";
    public static IMPORT_ATTRIBUTE_FROM_EXTERNAL_SYSTEM: string = "IMPORT_ATTRIBUTE_FROM_EXTERNAL_SYSTEM";
    public static EXPORT_ATTRIBUTE_TO_EXTERNAL_SYSTEM: string = "EXPORT_ATTRIBUTE_TO_EXTERNAL_SYSTEM";

    public static IMPORT_SO_FROM_EXTERNAL_SYSTEM: string = "IMPORT_SO_FROM_EXTERNAL_SYSTEM";
    public static IMPORT_OPPORTUNITY_FROM_EXTERNAL_SYSTEM = "IMPORT_OPPORTUNITY_FROM_EXTERNAL_SYSTEM";
    public static SALES_ORDER_IMPORT_AS_CASH_SALE = "SALES_ORDER_IMPORT_AS_CASH_SALE";
    public static UPDATE_SO_FROM_EXTERNAL_SYSTEM: string = "UPDATE_SO_FROM_EXTERNAL_SYSTEM";
    public static IMPORT_SO_GUEST_CUSTOMER: string = "IMPORT_SO_GUEST_CUSTOMER";
    public static IMPORT_SO_DUMMMY_ITEM: string = "IMPORT_SO_DUMMMY_ITEM";
    public static EXPORT_SO_TO_EXTERNAL_SYSTEM: string = "EXPORT_SO_TO_EXTERNAL_SYSTEM";
    public static EXPORT_SO_GUEST_CUSTOMER: string = "EXPORT_SO_GUEST_CUSTOMER";
    public static EXPORT_SO_DUMMMY_ITEM: string = "EXPORT_SO_DUMMMY_ITEM";
    public static EXPORT_SO_SYSTEM_NOTES: string = "EXPORT_SO_SYSTEM_NOTES";
    public static CANCEL_SO_FROM_EXTERNAL_SYSTEM: string = "CANCEL_SO_FROM_EXTERNAL_SYSTEM";
    public static CANCEL_SO_TO_EXTERNAL_SYSTEM: string = "CANCEL_SO_TO_EXTERNAL_SYSTEM";
    public static EXPORT_CUSTOMER_TO_EXTERNAL_SYSTEM: string = "EXPORT_CUSTOMER_TO_EXTERNAL_SYSTEM";
    public static IMPORT_CUSTOMER_FROM_EXTERNAL_SYSTEM: string = "IMPORT_CUSTOMER_FROM_EXTERNAL_SYSTEM";
    public static UPDATE_CUSTOMER_IF_EXISTS: string = "UPDATE_CUSTOMER_IF_EXISTS";
    public static EXPORT_ITEM_TO_EXTERNAL_SYSTEM: string = "EXPORT_ITEM_TO_EXTERNAL_SYSTEM";
    public static EXPORT_CATEGORY_TO_EXTERNAL_SYSTEM: string = "EXPORT_CATEGORY_TO_EXTERNAL_SYSTEM";
    public static IMPORT_ITEM_FROM_EXTERNAL_SYSTEM: string = "IMPORT_ITEM_FROM_EXTERNAL_SYSTEM";
    public static EXPORT_ITEM_TIERED_PRICING: string = "EXPORT_ITEM_TIERED_PRICING";
    public static UPDATE_ITEM_TO_EXTERNAL_SYSTEM: string = "UPDATE_ITEM_TO_EXTERNAL_SYSTEM";
    public static EXPORT_INVOICE_TO_EXTERNAL_SYSTEM: string = "EXPORT_INVOICE_TO_EXTERNAL_SYSTEM";
    public static EXPORT_CASH_REFUND_TO_EXTERNAL_SYSTEM: string = "EXPORT_CASH_REFUND_TO_EXTERNAL_SYSTEM";
    public static EXPORT_ITEM_FULFILLMENT_TO_EXTERNAL_SYSTEM: string = "EXPORT_ITEM_FULFILLMENT_TO_EXTERNAL_SYSTEM";
    public static EXPORT_ITEM_FULFILLMENT_TRACKING_INFO: string = "EXPORT_ITEM_FULFILLMENT_TRACKING_INFO";
    public static EXPORT_PROMOTION_TO_EXTERNAL_SYSTEM: string = "EXPORT_PROMOTION_TO_EXTERNAL_SYSTEM";
    public static EXPORT_PRICE_LEVEL_TO_EXTERNAL_SYSTEM: string = "EXPORT_PRICE_LEVEL_TO_EXTERNAL_SYSTEM";
    public static EXPORT_PAYMENT_TERMS_TO_EXTERNAL_SYSTEM: string = "EXPORT_PAYMENT_TERMS_TO_EXTERNAL_SYSTEM";
    public static IMPORT_ATTRIBUTE_FROM_EXTERNAL_SYSTEM: string = "IMPORT_ATTRIBUTE_FROM_EXTERNAL_SYSTEM";
    public static EXPORT_ATTRIBUTE_TO_EXTERNAL_SYSTEM: string = "EXPORT_ATTRIBUTE_TO_EXTERNAL_SYSTEM";
    public static IMPORT_CONTACT_FROM_EXTERNAL_SYSTEM: string = "IMPORT_CONTACT_FROM_EXTERNAL_SYSTEM";
    public static EXPORT_CONTACT_TO_EXTERNAL_SYSTEM: string = "EXPORT_CONTACT_TO_EXTERNAL_SYSTEM";
    public static IMPORT_ORDER_CANCELLATION_FROM_EXTERNAL_SYSTEM: string = "IMPORT_ORDER_CANCELLATION_FROM_EXTERNAL_SYSTEM";
    public static IMPORT_ORDER_FULFILLMENT_FROM_EXTERNAL_SYSTEM: string = "IMPORT_ORDER_FULFILLMENT_FROM_EXTERNAL_SYSTEM";
    public static IMPORT_SETTLEMENT_REPORT: string = "IMPORT_SETTLEMENT_REPORT";
    public static LIST_INBOUND_SHIPMENTS: string = "LIST_INBOUND_SHIPMENTS";
    public static ORDER_CANCELLATION_IMPORT: string = "ORDER_CANCELLATION_IMPORT";
    public static IMPORT_CASH_REFUND_FROM_EXTERNAL_SYSTEM: string = "IMPORT_CASH_REFUND_FROM_EXTERNAL_SYSTEM";
    public static IMPORT_CASH_REFUND_FROM_AMAZON: string = "IMPORT_CASH_REFUND_FROM_AMAZON";
    public static IMPORT_WALMART_CASH_REFUND_FROM_EXTERNAL_SYSTEM: string = "IMPORT_WALMART_CASH_REFUND_FROM_EXTERNAL_SYSTEM";
    public static SEND_ERROR_NOFTIFICATION = "SEND_ERROR_NOFTIFICATION";

}


